# Generated by Django 3.2.5 on 2021-07-27 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('warranty', models.BooleanField(default=False)),
                ('image1', models.ImageField(upload_to='uploads/photos/')),
                ('image2', models.ImageField(upload_to='uploads/photos/')),
                ('image3', models.ImageField(upload_to='uploads/photos/')),
                ('college', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.college')),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
