# Generated by Django 3.2.5 on 2021-07-27 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collegeitem',
            name='donator',
        ),
        migrations.RemoveField(
            model_name='collegeitem',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='collegeitem',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='collegeitem',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='collegeitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='collegeitem',
            name='warranty',
        ),
        migrations.AlterField(
            model_name='collegeitem',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.college'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('warranty', models.BooleanField(default=False)),
                ('image1', models.ImageField(upload_to='uploads/photos/')),
                ('image2', models.ImageField(upload_to='uploads/photos/')),
                ('image3', models.ImageField(upload_to='uploads/photos/')),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='collegeitem',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.item'),
        ),
    ]
