# Generated by Django 3.2.5 on 2021-07-27 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0002_auto_20210727_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeitem',
            name='items',
        ),
        migrations.AddField(
            model_name='collegeitem',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='collegeitem',
            name='donator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collegeitem',
            name='image1',
            field=models.ImageField(null=True, upload_to='uploads/photos/'),
        ),
        migrations.AddField(
            model_name='collegeitem',
            name='image2',
            field=models.ImageField(null=True, upload_to='uploads/photos/'),
        ),
        migrations.AddField(
            model_name='collegeitem',
            name='image3',
            field=models.ImageField(null=True, upload_to='uploads/photos/'),
        ),
        migrations.AddField(
            model_name='collegeitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collegeitem',
            name='warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
