# Generated by Django 3.2.5 on 2021-07-27 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0003_auto_20210727_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeitem',
            name='donator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collegeitem',
            name='image1',
            field=models.ImageField(upload_to='uploads/photos/'),
        ),
        migrations.AlterField(
            model_name='collegeitem',
            name='image2',
            field=models.ImageField(upload_to='uploads/photos/'),
        ),
        migrations.AlterField(
            model_name='collegeitem',
            name='image3',
            field=models.ImageField(upload_to='uploads/photos/'),
        ),
        migrations.AlterField(
            model_name='collegeitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
