# Generated by Django 3.2.5 on 2021-07-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cardDescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
